### ISSUE TITLE
libhybris issues for Fairphone 2 (FP2)

### ISSUE THREAD

**Issue by peat-psuwit** [Halium/projectmanagement#10]
Works
--------
- [x] test_egl_configs
- [x] test_lights
- [x] test_vibrator
- [x] test_gps

Doesn't work
-----------------
- [ ] test_audio
```
root@localhost:/# test_audio                                     
Audio device API version 0200 doesn't match platform current 3004.test_audio: test_audio.c:71: main: Assertion `audiohw->common.version == AUDIO_DEVICE_API_VERSION_CURRENT' failed.
Aborted
```

- [ ] test_camera
```
root@localhost:/# test_camera
ae-bracket-hdr=Off;ae-bracket-hdr-values=Off,AE-Bracket;antibanding=auto;antibanding-values=off,60hz,50hz,auto;auto-exposure=center-weighted;auto-exposure-lock=false;auto-exposure-lock-supported=true;auto-exposure-values=frame-average,center-weighted,spot-metering,center-weighted,spot-metering-adv,center-weighted-adv;auto-hdr-supported=true;auto-whitebalance-lock=false;auto-whitebalance-lock-supported=true;avtimer=disable;brightness-step=1;camera-mode=0;contrast=5;contrast-step=1;denoise=denoise-on;denoise-values=denoise-off,denoise-on;dis=disable;dis-values=enable,disable;effect=none;effect-values=none,mono,negative,solarize,sepia,posterize,whiteboard,blackboard,aqua,emboss,sketch,neon;exposure-compensation=0;exposure-compensation-step=0.25;face-detection=off;face-detection-values=off,on;flip-mode-values=off,flip-v,flip-h,flip-vh;focal-length=2.93;focus-distances=Infinity,Infinity,Infinity;focus-mode=fixed;focus-mode-values=fixed;hdr-need-1x=false;hfr-size-values=;histogram=disable;histogram-values=enable,disable;horizontal-view-angle=54.8;internal-restart=true;iso=auto;iso-values=auto,ISO_HJR,ISO100,ISO200,ISO400,ISO800,ISO1600,ISO3200;jpeg-quality=85;jpeg-thumbnail-height=288;jpeg-thumbnail-quality=85;jpeg-thumbnail-size-values=512x288,480x288,256x154,432x288,320x240,176x144,0x0;jpeg-thumbnail-width=512;lensshade=enable;lensshade-values=enable,disable;long-shot=off;longshot-supported=true;luma-adaptation=3;max-brightness=6;max-contrast=10;max-exposure-compensation=8;max-exposure-time=2000000;max-focus-pos-index=60;max-num-detected-faces-hw=5;max-num-detected-faces-sw=5;max-num-focus-areas=0;max-num-metering-areas=5;max-saturation=10;max-sce-factor=100;max-sharpness=36;max-wb-cct=8000;max-zoom=78;mce=enable;mce-values=enable,disable;metering-areas=(0, 0, 0, 0, 0);min-brightness=0;min-contrast=0;min-exposure-compensation=-8;min-exposure-time=200;min-focus-pos-dac=1023;min-focus-pos-index=40;min-saturation=0;min-sce-factor=-100;min-sharpness=0;min-wb-cct=2000;num-snaps-per-shutter=1;picture-format=jpeg;picture-format-values=jpeg,bayer-mipi-10bggr,bayer-ideal-qcom-10bggr,bayer-qcom-10bggr,yuv422sp;picture-size=160x120;picture-size-values=1600x1200,1280x960,1280x768,1280x720,1024x768,800x600,864x480,800x480,720x480,640x480,352x288,320x240,176x144,160x120;preferred-preview-size-for-video=1600x1200;preview-flip=off;preview-format=yuv420sp;preview-format-values=yuv420sp,yuv420p,nv12-venus;preview-fps-range=7500,30000;preview-fps-range-values=(15000,15000),(24000,24000),(7500,30000),(30000,30000);preview-frame-rate=30;preview-frame-rate-values=8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30;preview-size=1600x1200;preview-size-values=1600x1200,1280x960,1280x720,864x480,800x480,768x432,720x480,640x480,576x432,480x320,384x288,352x288,320x240,240x160,176x144,160x120;qc-camera-features=1151;qc-max-num-requested-faces=5;raw-size=1600x1200;redeye-reduction=disable;redeye-reduction-values=enable,disable;saturation=5;saturation-step=1;sce-factor-step=10;scene-detect=off;scene-detect-values=off,on;scene-mode=auto;scene-mode-values=auto,asd,landscape,snow,beach,sunset,night,portrait,backlight,sports,steadyphoto,flowers,candlelight,fireworks,party,night-portrait,theatre,action,AR,hdr;selectable-zone-af=auto;selectable-zone-af-values=auto,spot-metering,center-weighted,frame-average;sharpness=12;sharpness-step=6;skinToneEnhancement=0;skinToneEnhancement-values=enable,disable;smooth-zoom-supported=false;snapshot-picture-flip=off;supported-live-snapshot-sizes=1600x1200,1280x960,1280x768,1280x720,1024x768,800x600,864x480,800x480,720x480,640x480,352x288,320x240,176x144,160x120;touch-af-aec=touch-off;touch-af-aec-values=touch-off,touch-on;vertical-view-angle=42.5;video-flip=off;video-frame-format=yuv420sp;video-hfr=off;video-hfr-values=off;video-hsr=off;video-size=1600x1200;video-size-values=1600x1200,1280x960,1280x720,864x480,800x480,720x480,640x480,480x320,352x288,320x240,176x144,160x120;video-snapshot-supported=true;video-stabilization-supported=false;whitebalance=auto;whitebalance-values=auto,incandescent,fluorescent,warm-fluorescent,daylight,cloudy-daylight,twilight,shade,manual-cct;zoom=0;zoom-ratios=100,102,104,107,109,112,114,117,120,123,125,128,131,135,138,141,144,148,151,155,158,162,166,170,174,178,182,186,190,195,200,204,209,214,219,224,229,235,240,246,251,257,263,270,276,282,289,296,303,310,317,324,332,340,348,356,364,373,381,390,400,409,418,428,438,448,459,470,481,492,503,515,527,540,552,565,578,592,606;zoom-supported=true;zsl=off;zsl-hdr-supported=true;zsl-values=off,on 
Supported size: [1600,1200]
Supported size: [1280,960]
Supported size: [1280,768]
Supported size: [1280,720]
Supported size: [1024,768]
Supported size: [800,600]
Supported size: [864,480]
Supported size: [800,480]
Supported size: [720,480]
Supported size: [640,480]
Supported size: [352,288]
Supported size: [320,240]
Supported size: [176,144]
Supported size: [160,120]
Supported size: [1600,1200]
Supported size: [1280,960]
Supported size: [1280,720]
Supported size: [864,480]
Supported size: [800,480]
Supported size: [768,432]
Supported size: [720,480]
Supported size: [640,480]
Supported size: [576,432]
Supported size: [480,320]
Supported size: [384,288]
Supported size: [352,288]
Supported size: [320,240]
Supported size: [240,160]
Supported size: [176,144]
Supported size: [160,120]
Preview fps range: [7500,30000]
Current preview fps range: 30
Current preview size: [960,720]
Current picture size: [160,120]
Max zoom: 78 
Current effect mode: 0 
Current flash mode: 0 
Current wb mode: 0 
Current scene mode: 0 
Current af mode: 0 
Segmentation fault
```

- [ ] test_hwcomposer
```
root@localhost:/# test_hwcomposer       
width: 1080 height: 1920
OpenGL ES 3.0 V@84.0 AU@05.00.00.046.002 (CL@)
```
And it just hangs with nothing on screen.
- [ ] test_input
```
root@localhost:/# test_input 
on_new_event	EventType: 1 
	device_id: 5 
	source_id: 4098 
	action: 0 
	flags: 0 
	meta_state: 0 
	details.motion.event_time: 997476180000
Segmentation fault
```
On a touch event. Other events (such as buttons) seem to work.

- [ ] test_sensors
```
root@localhost:/# test_sensors  
Hardware module ID: sensors
Hardware module Name: QTI Sensors Module
Hardware module Author: Qualcomm Technologies, Inc.
Hardware module API version: 0x1
Hardware HAL API version: 0x100
Poll device version: 0x1030001
API VERSION 0.1 (legacy): 0x1
API VERSION 0.1: 0x65537
API VERSION 1.0: 0x16777217
API VERSION 1.1: 0x16842753
API VERSION 1.2: 0x16908289
API VERSION 1.3: 0x16973825
Got 24 sensors
=== Sensor 0 ==
Name: LSM330D Accelerometer
Vendor: STMicroelectronics
Version: 0x1
Handle: 0x0
Type: 1
Segmentation fault
```

Broken/skipped tests
-----------------
- [ ] test_wifi: it seems to work, but no change in wlan0 interface appearance.
- [ ] test_egl
- [ ] test_glesv2
- [ ] test_media
- [ ] test_nfc: FP2 doesn't have NFC.
- [ ] test_recorder

**Comment by z3ntu** [comment]
`test_hwcomposer` is probably the same issue I encountered while porting Plasma Mobile which is that something tries to continously open `/system/build.prop` (and also never closing it)... Attachment: [strace I did for Plasma Mobile](https://github.com/Halium/projectmanagement/files/1034118/output.txt)

Also:

> @z3ntu I had the same issue (blobs) on my OnePlus One. Couldn't figure out the problem.

> Cm12.1 and AOSP 5.1

**Comment by bhush9** [comment]
I am not sure if is same issue, I believe for you test_hwcomposer used to crash in the end right? but still strace and logcat during test_hwcomposer is run would be lovely @peat-psuwit

**Comment by z3ntu** [comment]
(I used `sudo EGL_PLATFORM=hwcomposer strace test_hwcomposer` for Plasma Mobile btw 😄)

**Comment by peat-psuwit** [comment]
logcat: http://paste.ubuntu.com/24690594/
strace: http://paste.ubuntu.com/24704553/
Note that they're from a different run.

I spotted failing ioctl to fd 3 with EPERM, digging into kernel.......

**Comment by z3ntu** [comment]
test_hwcomposer works with the latest rootfs (test_hwcompower didn't support hwcomposer version 1.4 so a patch had to be applied to the test)

**Comment by z3ntu** [comment]
* Audio works even though the test doesn't.
* Touchscreen input works even though the test doesn't.
* WiFi works (didn't manage to get it working with WPA2 Enterprise but with WPA2 Personal it works).

**Comment by z3ntu** [comment]
When ignoring the float issue with libhybris, the sensor test lists all sensors and then fails with `*** Error in '/root/libhybris/hybris/tests/.libs/test_sensors': free(): invalid pointer: 0xb6bd90a8 ***`

**Comment by z3ntu** [comment]
gps works too (after working around the printf bug)

**Comment by z3ntu** [comment]
test_camera crashes at
```
#0  0xb6fafbe6 in eglCreateWindowSurface () from /usr/lib/arm-linux-gnueabihf/libhybris-egl/libEGL.so.1
#1  0x00011bd8 in main (argc=<optimized out>, argv=<optimized out>) at test_camera.c:387
```

**Comment by peat-psuwit** [comment]
Superseded by #135.
