### ISSUE TITLE
[device-port] [star2lte] Samsung Galaxy S9+ (SM-G965F)

### ISSUE THREAD

**Issue by vidasov** [Halium/projectmanagement#121]
Tree: halium-7.1

- [x] Create manifest 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

$ breakfast star2lte
including vendor/cm/vendorsetup.sh
build/core/product_config.mk:254: *** _nic.PRODUCTS.[[device/samsung/star2lte/lineage.mk]]: "build/target/product/product_launched_with_o.mk" does not exist.  Stop.
build/core/product_config.mk:254: *** _nic.PRODUCTS.[[device/samsung/star2lte/lineage.mk]]: "build/target/product/product_launched_with_o.mk" does not exist.  Stop.
build/core/product_config.mk:254: *** _nic.PRODUCTS.[[device/samsung/star2lte/lineage.mk]]: "build/target/product/product_launched_with_o.mk" does not exist.  Stop.
Device star2lte not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Found repository: android_device_samsung_star2lte
Traceback (most recent call last):
  File "vendor/cm/build/tools/roomservice.py", line 263, in <module>
    default_revision = get_default_revision()
  File "vendor/cm/build/tools/roomservice.py", line 117, in get_default_revision
    return r.replace('refs/heads/', '').replace('refs/tags/', '')
AttributeError: 'NoneType' object has no attribute 'replace'
build/core/product_config.mk:254: *** _nic.PRODUCTS.[[device/samsung/star2lte/lineage.mk]]: "build/target/product/product_launched_with_o.mk" does not exist.  Stop.
build/core/product_config.mk:254: *** _nic.PRODUCTS.[[device/samsung/star2lte/lineage.mk]]: "build/target/product/product_launched_with_o.mk" does not exist.  Stop.

** Don't have a product spec for: 'lineage_star2lte'
** Do you have the right repo manifest?

**Comment by bachoudev** [comment]
This error seems to come from halium since we use the 7.1 version. star* device use 8.1.
Thx to @Herrie82 i found he had a pretty good repo for halium-8.1.
I got some errors using his halium 8.1 port so i forked it to solve some issues with starlte build.
You can get all my forked edit and doc here: https://github.com/bachoudev/ubports-starlte

i get a bootimage without any errors but i get somes when building systemimage.

The build failed with a strange python error:
import policy
ImportError: No module named policy

PS: I know my test was not on star2lte (i don't own this device) but starlte, star2lte can be built with the same based i think since the hardware is not really differents.

**Comment by bachoudev** [comment]
Fix some errors on "mka systemimage" so we have a boot image and system image build for starlte (i think we can apply all my edits for star2lte to get the same state).

i made a readme with all step to fix all errors here https://github.com/bachoudev/ubports-starlte/blob/master/README.md

i will test asap on my device.

**Comment by bachoudev** [comment]
So tested on my device and get stuck on knox boot.
Idk really know why.
I missed some kernel defconfigs it's now fixed but can't unset CONFIG_RT_GROUP_SCHED see detail error (https://github.com/bachoudev/ubports-starlte)

All problems seems to come from my device tree so halium 8.1 seems to work great. I get always 3 build bugs (seems makefile don't copy some file) idk if it comes for my device tree or halium 8.1 you can see detail here (https://github.com/bachoudev/ubports-starlte)

**Comment by 0110100001101001XD** [comment]
Hello, I just subscribed to github in order to help you. How can I help you?

**Comment by batowaves** [comment]
Hello there fellas. What is the latest situation. How may i assist you?

I cannot see star2lte in the device documentation list. I am willing to help you if it is not documented yet. Plus whatever help needed. Thanks!

**Comment by 0110100001101001XD** [comment]
My telegram account:
https://t.me/Themetaleye

a: batowaves ***@***.***>
Inviato: Venerdì 28 Maggio 2021, 19:19
A: Halium/projectmanagement
Cc: Luigi Ciapparelli - ***@***.***; Manual
Oggetto: Re: [Halium/projectmanagement] [device-port] [star2lte] Samsung Galaxy S9+ (SM-G965F) (#121)


Hello there fellas. What is the latest situation. How may i assist you?

I cannot see star2lte in the device documentation list. I am willing to help you if it is not documented yet. Plus whatever help needed. Thanks!

**Comment by 0110100001101001XD** [comment]
Contact me on telegram https://t.me/Themetaleye


________________________________
