### ISSUE TITLE
halium on cedric Golpe

### ISSUE THREAD

**Issue by Golpe82** [Halium/projectmanagement#263]
Tree: 

- [x] Create manifest 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by Golpe82** [comment]
when building  system image i got errors in 2 files, this are the solutions:
- `/home/x/halium/build/tools/check_radio_versions.py`  
``` python
except IOError:
    if not bad: print
    print("*** Error opening \"%s.sha1\"; can't verify %s" % (fn, key))
    bad = True
    continue
  for line in f:
    line = line.strip()
    if not line or line.startswith("#"): continue
    h, v = line.split()
    versions[h] = v

  if digest not in versions:
    if not bad: print
    print("*** SHA-1 hash of \"%s\" doesn't appear in \"%s.sha1\"" % (fn, fn))
    bad = True
    continue

  if versions[digest] not in values:
    if not bad: print
    print("*** \"%s\" is version %s; not any %s allowed by \"%s\"." % (
        fn, versions[digest], key, sys.argv[1]))
    bad = True
```


- `/home/x/halium/build/tools/post_process_props.py`:
```  python
    for key, value in buildprops.items():
    # Check build properties' length.
```

**Comment by Golpe82** [comment]
getting error
``` bash
Traceback (most recent call last):
  File "/home/golpe/halium/out/host/linux-x86/bin/insertkeys.py", line 5, in <module>
    import ConfigParser
ModuleNotFoundError: No module named 'ConfigParser'

```

solved with
line 5 `import configparser`
line 111 `class ParseConfig(configparser.ConfigParser):`
in `out/host/linux-x86/bin/insertkeys.py`

**Comment by Golpe82** [comment]
getting error
``` bash
Traceback (most recent call last):
  File "/home/golpe/halium/out/host/linux-x86/bin/insertkeys.py", line 260, in <module>
    key_map = config.generateKeyMap(options.target_build_variant.lower(), options.key_directory)
  File "/home/golpe/halium/out/host/linux-x86/bin/insertkeys.py", line 141, in generateKeyMap
    keyMap[tag] = GenerateKeys(path)
  File "/home/golpe/halium/out/host/linux-x86/bin/insertkeys.py", line 84, in __init__
    sys.exit("Detected erroneous line \""+ line + "\" on " + str(lineNo)
TypeError: can only concatenate str (not "bytes") to str
```

solved with:
line 84 `sys.exit("Detected erroneous line \""+ line.decode("utf-8") + "\" on " + str(lineNo)`
in `out/host/linux-x86/bin/insertkeys.py`

**Comment by Golpe82** [comment]
getting error:
``` bash
Detected erroneous line "-----BEGIN CERTIFICATE-----" on 1 in pem file: build/target/product/security//platform.x509.pem
```
