### ISSUE TITLE
[device-port] OnePlus 5 (cheeseburger)

### ISSUE THREAD

**Issue by dragynbane222** [Halium/projectmanagement#45]
[Manifest](https://gist.github.com/dragynbane222/68fc2666fb195536db7173b46a01a197)

Progress so far:
Literally nothing but the initial source setup. Will update when more progress has been made.

**Comment by LNJ2** [comment]
In case you missed it (its not in the doc) please always update the manifest in halium-devices. Thank you. :smiley:

**Comment by dragynbane222** [comment]
LNJ2, thanks for the tip. I'm editing that file now, Took me quite some time to find time to work on this, real life sometimes sucks in that sense...

**Comment by dragynbane222** [comment]
So as the update says, I had issues getting hybrisboot to build, turns out it was a missing libssl-dev package that wasn't documented as a required dependency. Bug filed. I think I've almost got the entire thing to build. just waiting on the system image to build.

**Comment by dragynbane222** [comment]
I ran into issues I know not how to fix, so I kind of came to the realization that I got in over my head. Someone else is free to pick this up, but this is beyond what I can do.

**Comment by Stefano0101** [comment]
Upon running breakfast it errors out currently. How did you fix it? 
this is the repo and it gives me an error when running breakfast.

~/halium$ breakfast cheeseburger
including vendor/cm/vendorsetup.sh
build/core/product_config.mk:249: *** Can not locate config makefile for product "lineage_cheeseburger". Stop.
build/core/product_config.mk:249: *** Can not locate config makefile for product "cm_cheeseburger". Stop.
build/core/product_config.mk:249: *** Can not locate config makefile for product "lineage_cheeseburger". Stop.
Device cheeseburger not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Found repository: android_device_oneplus_cheeseburger
Traceback (most recent call last):
  File "vendor/cm/build/tools/roomservice.py", line 263, in <module>
    default_revision = get_default_revision()
  File "vendor/cm/build/tools/roomservice.py", line 117, in get_default_revision
    return r.replace('refs/heads/', '').replace('refs/tags/', '')
AttributeError: 'NoneType' object has no attribute 'replace'
build/core/product_config.mk:249: *** Can not locate config makefile for product "lineage_cheeseburger". Stop.
build/core/product_config.mk:249: *** Can not locate config makefile for product "lineage_cheeseburger". Stop.

** Don't have a product spec for: 'lineage_cheeseburger'
** Do you have the right repo manifest?

**Comment by dragynbane222** [comment]
Breakfast ended up not being viable, I used lumch to do everything. "lunch cheeseburger" seemed to do what was needed.

**Comment by dragynbane222** [comment]
You'll want to run lunch with no arguments, though, it's better to make sure you're using the version with "eng" in it, as userdebug causes issues down the road.

**Comment by Stefano0101** [comment]
But this is for 7.1 , I don't think Cheeseburger has 5.1 ever installed, so how can that build halium without files needed?

**Comment by alckanso** [comment]
Any progress on port for OnePlus 5?

**Comment by Stefano0101** [comment]
I no longer have the device, so from my side no.

**Comment by Vince1171** [comment]
Hi, I'm trying to compile halium/hybris for the Oneplus 5. But it seems that the current repo is uncompilable....  in my case, I have a lot of clang errors, due to a non-findable clang binary and an unknown error "-Wno-vectorizer-no-neon"...
any idea? I have tried with the repo from Lineage, and there are no compilation errors but it doesn't boot.
Has anyone manage to boot halium on the OP5 with the current repo or can I start from scratch with the repo from Lineage and override the current repos?

**Comment by Stefano0101** [comment]
I have built the halium and system.img successfully, but upon installing the lxc was bootlooping just like Op3t. I used Lineage repo as well, but that was it.

**Comment by Vince1171** [comment]
> I have built the halium and system.img successfully, but upon installing the lxc was bootlooping just like Op3t. I used Lineage repo as well, but that was it.

Do you still have your repos somewhere? or the changes you made into?
My port currently don't boot at all, and don't provide any usb tethering ether...

**Comment by Stefano0101** [comment]
no, sorry @Vince1171 I don't have it anymore, nor built images/halium.

**Comment by Inokinoki** [comment]
I'm willing to continue the work. Thanks very much for all your information which helps me build an image for op5.

Up to now, it seems that the `system.img` and `hybris-boot.img` is built successfully.

I'm going to validate whether it will work.

**Comment by Aplexw** [comment]
Any news on what`s happening ? Is there any one working on this project ? I own an oneplus 5 and i want to install ubports

**Comment by Vince1171** [comment]
> Any news on what`s happening ? Is there any one working on this project ? I own an oneplus 5 and i want to install ubports

sorry for the (very) late response
yes a port is on-going and it's very promising
we still have to fix some bugs before releasing it to the public (call stuff is a pain)

**Comment by oknyshuk** [comment]
> > Any news on what`s happening ? Is there any one working on this project ? I own an oneplus 5 and i want to install ubports
> 
> sorry for the (very) late response
> yes a port is on-going and it's very promising
> we still have to fix some bugs before releasing it to the public (call stuff is a pain)

How is it going? I own OP5 too, should I wait for something?
