### ISSUE TITLE
[device-port] [oneplus3] Port to OnePlus 3(T)

### ISSUE THREAD

**Issue by vanyasem** [Halium/projectmanagement#63]
This port is based on the 7.1 branch of Halium

### Progress:
- [x] Create manifest containing kernel, vendor, and device trees
- [x] Build hybris-boot (`hybris-boot.img`) and systemimage (`system.img`)
- [x] Initial flash & boot 
  - [x] Format `/data` to get rid of encryption
  - [x] Boot into initrd debugging (telnet)
  - [x] Boot into rootfs (ssh)
- [ ] Get LXC running 
- [ ] Get Wi-Fi working
- [ ] libhybris tests 
  - [ ] test_audio _(broken)_
  - [ ] test_camera _(broken)_
  - [ ] test_egl _(broken)_
  - [ ] test_egl_configs
  - [ ] test_glesv2 _(broken)_
  - [ ] test_gps
  - [ ] test_hwcomposer
  - [ ] test_input _(broken)_
  - [ ] test_lights
  - [ ] test_media _(broken)_
  - [ ] test_nfc _(broken)_
  - [ ] test_recorder _(broken)_
  - [ ] test_sensors 
  - [ ] test_vibrator
  - [ ] test_wifi _(broken)_
- [ ] Test various rootfs
  - [ ] [UBports rootfs](http://ci.ubports.com/job/xenial-7.1-caf-sudoku-rootfs/) _(boots, no ssh)_
  - [ ] [Plasma Mobile rootfs](http://images.plasma-mobile.org/caf-rootfs/) _(boots, no lxc)_
  - [ ] [LuneOS rootfs](http://www.webos-ports.org)
  - [ ] [Arch rootfs](https://github.com/Halium/rootfs-builder/tree/archlinux)
  - [ ] [Debian rootfs](https://github.com/debian-pm/rootfs-builder/tree/debian)
  - [ ] Fedora rootfs
  - [ ] Gentoo rootfs

*Sidenote 1:* As @UniversalSuperBox suggests me not to fork the vendor repo, it has to be manually patched. You need to remove `vendor/oneplus/oneplus3/proprietary/etc/thermal-engine.conf:system/etc/thermal-engine.conf` from `oneplus3-vendor.mk`

*Sidenote 2:* Some tests are broken in Halium 7.1. They won't work until they get fixed

**Kernel source:** https://github.com/Halium/android_kernel_oneplus_msm8996
**Device tree:** https://github.com/Halium/android_device_oneplus_oneplus3
**Repo Manifest:** https://github.com/Halium/halium-devices/blob/halium-7.1/manifests/oneplus_oneplus3.xml
**Build instructions:** TO BE WRITTEN

> This is a co-op port by @vanyasem, @sk8higher, and @mariogrip

**Comment by sk8higher** [comment]
Debug pastes from my device:
[Plasma Services + Mount](https://paste.ubuntu.com/p/NqG3pVYtNk/)
[Plasma Dmesg](https://paste.ubuntu.com/p/jvb3gSN5W5/)
[Plasma systemctl status](https://paste.ubuntu.com/p/JHRVkMt9H6/)
[Plasma lxc-checkconfig](https://paste.ubuntu.com/p/K52tGRN6Mx/)
[Plasma /proc/config.gz](https://paste.ubuntu.com/p/C6SpJ7Sm49/)
[Plasma EGL Configs](https://paste.ubuntu.com/p/BzbkpR8X2K/)
[Plasma Failing Hybris tests](https://paste.ubuntu.com/p/VR7YJbcpd4/)

**Comment by miketth** [comment]
This project looks awesome and I would like to test, but I can't find a sane tutorial. I don't know if I should post this here, but it seems like these problems only exist on this phone:
With halium-install from the halium-scripts repo the install fails on unpacking the rootfs
With JBBgameich/halium-install the install seems to work, but after issuing the command to continue the boot from telnet, the phone only has a white LED and a blank screen. Also /target only contains the data folder.

**Comment by vanyasem** [comment]
@PhotonMike that's okay, it's expected. everything you've mentioned is expected

**Comment by PhotonMike** [comment]
I somehow got it to work today and it successfully boots and has graphics, but the touch isn't working. But with an OTG adapter and a mouse, it works.
I know people hate getting asked for ETAs, but when is touch going to be sorted?
This is a really cool and useful OS for Linux and OSS enthusiasts and thanks for your work!

**Comment by vanyasem** [comment]
@PhotonMike could your please provide me with some pictures?

**Comment by PhotonMike** [comment]
I only have a crappy picture, as I had to take it with my laptop's webcam:
[https://imgur.com/a/LSkd4c8](https://imgur.com/a/LSkd4c8)

**Comment by vanyasem** [comment]
Regarding touch: https://paste.ubuntu.com/p/nJt4CfQRVr/ (`udevadm info /dev/input/event4`) 
It needs a magic udev rule in order to work. See last udev rule here: [70-yuga.rules](https://github.com/Halium/lxc-android/blob/master/usr/lib/lxc-android/) (don't forget to change `event1` to `event4`).

**Comment by vanyasem** [comment]
That didn't really work ^
Investigating :P

**Comment by vanyasem** [comment]
[Plasma udevadm info](https://paste.ubuntu.com/p/7H5ywDr62T/) after the fix above

**Comment by hu19960925** [comment]
I love Ubuntu touch very much, but I won't transplant. I'm glad to see you transplanting. I don't see the progress of transplanting, and I don't know where to go. I add three mobile phones. I haven't seen any updates lately, I hope you can see the migration.

**Comment by CodingMarco** [comment]
@PhotonMike How did you get graphics working? I also have an ssh connection right now and I think this might also be interesting for others...

**Comment by hu19960925** [comment]
I love Ubuntu touch very much, but I won't transplant. I'm glad to see you transplanting. I don't see the progress of transplanting, and I don't know where to go. I add three mobile phones. I haven't seen any updates lately, I hope you can see the migration.

**Comment by hu19960925** [comment]
想参与其中。不知道如何操作。

**Comment by SohnyBohny** [comment]
@hu19960925 https://t.me/UBports_Chinese

**Comment by hu19960925** [comment]
@

> @hu19960925 https://t.me/UBports_Chinese

需要翻墙才可以。

**Comment by WaaromZoMoeilijk** [comment]
Could anyone tell me what to do to contribute to this port

**Comment by hu19960925** [comment]
> 有人能告诉我如何为这个港口做贡献吗？

继续移植就可以了

**Comment by hu19960925** [comment]
我应该怎么联系你们呢。本人十分期待一加三手机 ubuntutouch. 可以发红包提高下大家的积极性。想加入其中但是不知道需要学习哪方面知识。

**Comment by hu19960925** [comment]
Hello, is this an Ubuntu touch for op3?

**Comment by miketth** [comment]
This is Halium, which is a foundation many mobile Linux distros use, like Ubuntu Touch or Plasma mobile. This is not Ubuntu Touch itself, this is what is needed to get Ubuntu working on the OnePlus 3.

**Comment by idontknow420** [comment]
is halium working perfectly for oneplus 3 ? how to get builds

**Comment by miketth** [comment]
@idontknow420 just check the first message in this issue.

**Comment by vanyasem** [comment]
I need a new tester for this device. Reach out to me at https://t.me/vanyasem

**Comment by sk8higher** [comment]
@vanyasem can I help?

**Comment by hu19960925** [comment]
> 我需要一个新的测试器。向我伸出手https://t.me/vanyasem

I have the equipment. How do I join the test

**Comment by idontknow420** [comment]
Sorry, i don't have this mobile . I asked because i want to confirm myself before buying this op3 for plasma / ubport stable build. :) i hope very soon we will get this stable build. 

Thank you in advance.

**Comment by kiranreddyrebel** [comment]
hi, any updates for this op3 ?

**Comment by vanyasem** [comment]
@Stefano0101 tested Plasma Mobile Edge (18.04) on his phone

It gets to GUI, Wi-Fi / Vibration / Lights work, but the touchscreen is still broken

Worth noting that `udev` rules were _not_ automatically copied, because for some reason [this Lineage build](https://forum.xda-developers.com/oneplus-3t/development/rom-t3556604) has [no](https://paste.ubuntu.com/p/jkgJCg84Zj/) `ro.product.device` in `/system/build.prop`

**Logs:**
[mount](https://paste.ubuntu.com/p/dNYgskZxyc/)
[lxc-checkconfig](https://paste.ubuntu.com/p/MW9q4GyqG3/)
[systemctl status](https://paste.ubuntu.com/p/b6Jks6jQJ4/)
[udevadm info /dev/input/event4](https://paste.ubuntu.com/p/nqdbDTQcHT/) # touchscreen
[udevadm info /dev/input/*](https://paste.ubuntu.com/p/2gkGrbBy3r/)
_NEW:_ [getevent](https://paste.ubuntu.com/p/K48GDV3k7N/)

**Comment by vanyasem** [comment]
@Stefano0101 tested UBports Edge on his phone

_ubports does not check for config_dummy, and thus doesn't drop into telnet with the current defconfig_

`ssh` is finally working now. The issue was that HostKeys (`/etc/ssh/ssh_host*`) were not auto-generated, and I had to `dpkg-reconfigure openssh-server`, as with plasma

The container is running, but Android [seems to bootloop](https://paste.ubuntu.com/p/ZpBkfcXwWz/) in it

No libhybris tests passed. I've noticed that `/android/firmware` is mounted as a `tmpfs` (instead of `vfat`) and is empty
```
root@ubuntu-phablet:~# test_vibrator 
Segmentation fault
```

`lxc-checkconfig` shows `Cgroup namespace: required`, which requires a kernel rebuild with minor defconfig changes
```
lxc-attach: cgroups/cgfs.c: lxc_cgroupfs_attach: 2538 could not move attached process 29573 to cgroup of container
```

**Logs:**
[lxc-checkconfig](https://paste.ubuntu.com/p/fMg3HXybv7/)
[mount](https://paste.ubuntu.com/p/MsjmcBMzqm/)
[getevent](https://paste.ubuntu.com/p/jqPRSHvMq5/)
[udevadm info /dev/input/*](https://paste.ubuntu.com/p/67gv8wG2xG/)

**screenfetch:**
![photo_2018-11-08_19-54-24](https://user-images.githubusercontent.com/13350458/48215227-dd294580-e392-11e8-9767-ce18faebfb7f.jpg)

**Comment by testingweb624** [comment]
Hi vanyasem, do we have any surprise sir ? Christmas is coming ahead. :D

**Comment by Stefano0101** [comment]
Yeah, I wouldn't mind a Christmas present(working Op3 port) :-)

**Comment by Stefano0101** [comment]
And maybe we should poke @mariogrip as well (he is also on this one ) :-)

**Comment by duckartes** [comment]
Is calling / text supported? 

Willing to test builds and post logs to help.

**Comment by vanyasem** [comment]
@duckartes no

**Comment by Stefano0101** [comment]
@vanyasem I wish it was :-)

**Comment by paranoidnela** [comment]
Hello, I'm interested in this port, I am currently trying to test what was already made out and I can't get past the oneplus logo with no led at all, I don't get any obvious errors either so I am really lost...
All I did was download the prebuilt images and follow the install documentation.

**Comment by vanyasem** [comment]
@Davidescion this port is not consumer-ready. unless you are a developer, you should not install the images

**Comment by kiranreddyrebel** [comment]
May we know if mariogrip has any minimal working port ? This device is powerful than other devices. It has 6GB RAM . I don't know why development has stopped.

**Comment by paranoidnela** [comment]
@vanyasem I might not be a developer but I’m familiar with this kind of thing, I just wasn’t able to get the phone to the infamous black screen with white led and I was wondering what did I do wrong.

**Comment by paranoidnela** [comment]
@kiranreddyrebel he probably doesn’t have that much time and touch in a real issue

**Comment by testingweb624** [comment]
Hi, did anyone tried UB OTA-7 with this port halium. It has new  libhybris and N drivers linker to make halium port easy , new android-caf Mir platform for qualcomm display.

**Comment by Stefano0101** [comment]
Hi testingweb624,
I did try, it built successfully hybris-boot, halium-boot and system.img, but I can't ssh into phone for some strange reason. Trying to set ssh and have this issue: sudo ip link set enp0s20f0u1 address 02:11:22:33:44:55
RTNETLINK answers: Device or resource busy   What to do to set the ssh? Anyone?

**Comment by testingweb624** [comment]
check this @Stefano0101  https://forums.ubports.com/topic/431/porting-halium-to-nexus-7-deb
Here it has some steps to do for connecting to ssh. It may help you.

**Comment by testingweb624** [comment]
Hi, @Stefano0101 ,plz check above link.  

If you don't mind can you paste the commands from your history (terminal) , How you exactly followed to succesfully build the Halium images. ?

**Comment by Stefano0101** [comment]
@testingweb624 , when I find a little time I upload it. Or/and I can share the files if you're interested.

**Comment by testingweb624** [comment]
I will run in my vps server, i just need the commands bro. Thank you for asking.

have checked above link. its helpful try those.

**Comment by Stefano0101** [comment]
@testingweb624  here I send you the commands. 
[Commands to build Halium for Op3(t).txt](https://github.com/Halium/projectmanagement/files/2882137/Commands.to.build.Halium.for.Op3.t.txt)

**Comment by idontknow420** [comment]
Thank you very much bro. Now I will play.

**Comment by Stefano0101** [comment]
@idontknow420  not a problem, let me know if you have any success with it.

**Comment by vanyasem** [comment]
The image server is up again

**Comment by testingweb624** [comment]
any improvements in op3 ? @vanyasem 
just casually asking bro .

**Comment by Vince1171** [comment]
if anyone want to test UT on Oneplus3
https://github.com/Vince1171/OnePlus3-T-Halium-Prebuild/
It in early stage, so don't expect much
I'll PR the changes soon

**Comment by cheshirean** [comment]
Hello! I am having problems installing UT on my device. Using the prebuild images, I followed the instructions from here - https://github.com/Vince1171/OnePlus3-T-Halium-Prebuild/
As a result, after a reboot, I get a screen with the words "charging ?? / 100" and that's it. There is no telnet, no ssh ... What am I doing wrong?

**Comment by Vince1171** [comment]
@Cheshirean  you are on charging mode (your phone is off and charging)
so you just have to power it up.
And I suggest you to use the v0.6 as I fixed the "charging ??/100". Now there is a proper charging animation

**Comment by cheshirean** [comment]
> @Cheshirean you are on charging mode (your phone is off and charging)
> so you just have to power it up.
> And I suggest you to use the v0.6 as I fixed the "charging ??/100". Now there is a proper charging animation

It's strange, I just made a "reset" of the fastboot before this ...
Nevertheless, the question remains the same. Trying yesterday again, I get either the same message or a hanging OnePlus logo. And I also do not have access to the device either on the ssh or telnet...

**Comment by Vince1171** [comment]
> > @Cheshirean you are on charging mode (your phone is off and charging)
> > so you just have to power it up.
> > And I suggest you to use the v0.6 as I fixed the "charging ??/100". Now there is a proper charging animation
> 
> It's strange, I just made a "reset" of the fastboot before this ...
> Nevertheless, the question remains the same. Trying yesterday again, I get either the same message or a hanging OnePlus logo. And I also do not have access to the device either on the ssh or telnet...

there was an error in my docs
the link to the rootfs was pointing to the edge rootfs (which is broken on OP3(t) )
this is link to the correct rootfs
https://ci.ubports.com/job/xenial-rootfs-armhf/lastSuccessfulBuild/artifact/out/ubports-touch.rootfs-xenial-armhf.tar.gz

**Comment by cheshirean** [comment]
> there was an error in my docs
> the link to the rootfs was pointing to the edge rootfs (which is broken on OP3(t) )
> this is link to the correct rootfs
> https://ci.ubports.com/job/xenial-rootfs-armhf/lastSuccessfulBuild/artifact/out/ubports-touch.rootfs-xenial-armhf.tar.gz

I tried with the new rootfs, it worked. I am successfully connecting via ssh. But i have new problem:
```
phablet@ubuntu-phablet:~$ anbox-tool install
Anbox kernel is not installed! Please flash this first!
```
I also saw the update [README.md](https://github.com/Vince1171/OnePlus3-T-Halium-Prebuild/), but have not yet had time to test them. Probably should build new images

**Comment by cheshirean** [comment]
Tried to build images with the manifest specified [here](https://github.com/Vince1171/OnePlus3-T-Halium-Prebuild/). As a result:
```
$ breakfast oneplus3
build/core/product_config.mk:268: *** No matches for product "lineage_oneplus3".  Останов.
build/core/product_config.mk:268: *** No matches for product "cm_oneplus3".  Останов.
build/core/product_config.mk:268: *** No matches for product "lineage_oneplus3".  Останов.
Device oneplus3 not found. Attempting to retrieve device repository from LineageOS Github (http://github.com/LineageOS).
Found repository: android_device_oneplus_oneplus3
Traceback (most recent call last):
  File "vendor/cm/build/tools/roomservice.py", line 263, in <module>
    default_revision = get_default_revision()
  File "vendor/cm/build/tools/roomservice.py", line 117, in get_default_revision
    return r.replace('refs/heads/', '').replace('refs/tags/', '')
AttributeError: 'NoneType' object has no attribute 'replace'
build/core/product_config.mk:268: *** No matches for product "lineage_oneplus3".  Останов.
build/core/product_config.mk:268: *** No matches for product "lineage_oneplus3".  Останов.

** Don't have a product spec for: 'lineage_oneplus3'
** Do you have the right repo manifest?
```

**Comment by Vince1171** [comment]
@Cheshirean try with ```breakfast halium_oneplus3-userdebug```

for the Anbox issue, are you sure you're using my prebuild boot image?
anbox binder should be integrated

**Comment by cheshirean** [comment]
@Vince1171, i was sure to your answer... You can give a link to exactly the right images and I will recheck? Thanks)

**Comment by Vince1171** [comment]
@Cheshirean   https://github.com/Vince1171/OnePlus3-T-Halium-Prebuild/releases
Anbox binder is integrated since v0.4
As there is an issue with the permission of ```anbox-tool```, you'll need this command in order to install it ```sudo python3 /system/halium/usr/bin/anbox-tool install```
and be aware that anbox is not stable at all, even on officially supported device

**Comment by cheshirean** [comment]
@Vince1171, i'm trying v0.4 and etc., and all work fine. Thanks for your help

**Comment by kiranreddyrebel** [comment]
Hi, any new updates on this device please.

**Comment by Vince1171** [comment]
@kiranreddyrebel
You can find news/updates for Ubuntu Touch [here](https://github.com/Vince1171/OnePlus3-T-Halium-Prebuild)
For other OS's, there are no news unfortunately

**Comment by ghost** [comment]
I've been trying to build an image to use with plasma mobile, but something SELinux related is causing issues:
```
[ 17% 3845/22153] build /home/user/halium/out/target/product/oneplus3/obj/ETC/sepolicy_intermediates/sepolicy
FAILED: /bin/bash -c "(/home/user/halium/out/host/linux-x86/bin/checkpolicy -M -c 30 -o /home/user/halium/out/target/product/oneplus3/obj/ETC/sepolicy_intermediates/sepolicy.tmp /home/user/halium/out/target/product/oneplus3/obj/ETC/sepolicy_intermediates/policy.conf ) &&
(/home/user/halium/out/host/linux-x86/bin/checkpolicy -M -c 30 -o /home/user/halium/out/target/product/oneplus3/obj/ETC/sepolicy_intermediates//sepolicy.dontaudit /home/user/halium/out/target/product/oneplus3/obj/ETC/sepolicy_intermediates/policy.conf.dontaudit ) && (/hom
e/user/halium/out/host/linux-x86/bin/sepolicy-analyze /home/user/halium/out/target/product/oneplus3/obj/ETC/sepolicy_intermediates/sepolicy.tmp permissive > /home/user/halium/out/target/product/oneplus3/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ) && (if [
\"userdebug\" = \"user\" -a -s /home/user/halium/out/target/product/oneplus3/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains ]; then echo \"==========\" 1>&2;               echo \"ERROR: permissive domains not allowed in user builds\" 1>&2;             echo \"Li
st of invalid domains:\" 1>&2;          cat /home/user/halium/out/target/product/oneplus3/obj/ETC/sepolicy_intermediates/sepolicy.permissivedomains 1>&2;                exit 1;                 fi ) && (mv /home/user/halium/out/target/product/oneplus3/obj/ETC/sepolicy_inte
rmediates/sepolicy.tmp /home/user/halium/out/target/product/oneplus3/obj/ETC/sepolicy_intermediates/sepolicy )"
vendor/cm/sepolicy/qcom/mpdecision.te:2:ERROR 'unknown type sysfs_devices_system_iosched' at token ';' on line 40157:
allow mpdecision sysfs_devices_system_iosched:file { { getattr open read ioctl lock } { open append write lock } };
#line 1 "vendor/cm/sepolicy/qcom/mpdecision.te"
checkpolicy:  error(s) encountered while parsing configuration
/home/user/halium/out/host/linux-x86/bin/checkpolicy:  loading policy configuration from /home/user/halium/out/target/product/oneplus3/obj/ETC/sepolicy_intermediates/policy.conf
[ 17% 3845/22153] host C: sefcontext_compile <= external/libselinux/utils/sefcontext_compile.c
ninja: build stopped: subcommand failed.
build/core/ninja.mk:151: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1
make: Leaving directory '/home/user/halium'

#### make failed to build some targets (08:01 (mm:ss)) ####
```

I've commented out the SELinux lines for now to get it to build, any ideas on how to fix it properly?

**Comment by TheBluestBird** [comment]
Hey everyone,is the project alive? I just got the device and wish to experiment/help

**Comment by SohnyBohny** [comment]
> Hey everyone,is the project alive? I just got the device and wish to experiment/help

Yeah, maybe more than ever :tada:

See https://github.com/Vince1171/OnePlus3-T-Halium-Prebuild/ and https://forums.ubports.com/topic/3253/oneplus-3-3t for more details

**Comment by linsmod** [comment]
hi, I have compiled the halium project for op3 successfully , thank gentleman  's help (https://github.com/Halium/android_device_oneplus_oneplus3/issues/8) and thank @Vince1171  's  document (https://github.com/Vince1171/OnePlus3-T-Halium-Prebuild#how-to-compile) 


I noticed that the release page provides the armhf version of ubuntu touch rootfs, 
however the ubports-installer i tried previously is installed an arm64 edge version, i got confused.
If installing the arm64 version of ubrootfs, how to?

I'm new here and I want to learn how to build the halium image (i made it) and install the ubuntu-touch on my device (oneplus3) step by step, thanks if any help. :)

**Comment by linsmod** [comment]
I know somewhere must has some docs about how-to,,, but not sure is it updated with the porting progress.  So if we list it here, may help more people.

**Comment by ernesst** [comment]
For the UBports rootfs : https://ci.ubports.com/job/xenial-hybris-edge-rootfs-arm64/

**Comment by linsmod** [comment]
> For the UBports rootfs : https://ci.ubports.com/job/xenial-hybris-edge-rootfs-arm64/

thanks, I'm trying to flush.

**Comment by linsmod** [comment]
an error:
<pre><font color="#4CE64C"><b>tiny@tiny-Lenovo-V480</b></font>:<font color="#295FCC"><b>~/halium</b></font>$ halium-scripts/halium-install ~/ubuntu-touch-rootfs/ubuntu-touch-hybris-xenial-edge-arm64-rootfs.tar.gz out/target/product/oneplus3/system.img 
please make sure the device is attched via USB in recovery mode

cleaning up
error: device unauthorized.
This adb server&apos;s $ADB_VENDOR_KEYS is not set
Try &apos;adb kill-server&apos; if that seems wrong.
Otherwise check for a confirmation dialog on your device.
<font color="#4CE64C"><b>tiny@tiny-Lenovo-V480</b></font>:<font color="#295FCC"><b>~/halium</b></font>$ 
</pre>

**Comment by linsmod** [comment]
I resolved the problem by replace the ubports recovery to twrp recovery. :)

**Comment by GetAGripGal** [comment]
Heya, how well does plasma mobile work with this? If at all?

**Comment by ComLarsic** [comment]
Heya, how well does plasma mobile work with this? If at all?

**Comment by vanyasem** [comment]
@ComLarsic please read the issue

**Comment by GetAGripGal** [comment]
@vanyasem I did, however there arent many updates on how it works, would like to install PM on my phone

**Comment by vanyasem** [comment]
@ComLarsic because it's not consumer ready frankly. and if you cannot read the docs, you probably shouldn't be playing with Halium

**Comment by GetAGripGal** [comment]
@vanyasem i can read the docs, was just looking for information about this specific device. But thx for your help I guess.

**Comment by vanyasem** [comment]
@ComLarsic well in that case the issue has all the information you might need, feel free to ask any specific questions if you get stuck

**Comment by kozlovandrei** [comment]
Plasma Mobile is not running. Help me. Ubuntu Touch is running.

**Comment by kozlovandrei** [comment]
phablet@localhost:~$ dmesg | grep .img
[    2.493268] initrd: Halium rootfs is /tmpmnt/rootfs.img 
[    2.509579] initrd: mounting  /tmpmnt/rootfs.img (user mode)
[    2.514577] initrd: mounting android system image (/tmpmnt/system.img) ro, in /android-system (system mode)
[    2.978920] systemd[1]: Mounting mount system.img...
[    2.986117] systemd[1]: Failed to mount mount system.img.
[    3.002077] systemd[1]: Mounting mount system.img...
[    3.007547] systemd[1]: Failed to mount mount system.img.
[    3.035222] systemd[1]: Mounting mount system.img...

**Comment by kozlovandrei** [comment]
Why system.img may not be mounted?

**Comment by kozlovandrei** [comment]
phablet@localhost:~$ dmesg | grep mount      
[    2.429140] Begin: Running /scripts/nfs-premount ... done.
[    2.429340] Begin: Running /scripts/local-premount ... done.
[    2.444134] EXT4-fs (sda15): couldn't mount as ext3 due to feature incompatibilities
[    2.444501] EXT4-fs (sda15): couldn't mount as ext2 due to feature incompatibilities
[    2.450505] EXT4-fs (sda15): mounted filesystem with ordered data mode. Opts: errors=remount-ro
[    2.475224] initrd: mounting /dev/sda15
[    2.486967] EXT4-fs: Warning: mounting with data=journal disables delayed allocation and O_DIRECT support!
[    2.486985] EXT4-fs (sda15): couldn't mount as ext3 due to feature incompatibilities
[    2.490510] EXT4-fs (sda15): mounted filesystem with journalled data mode. Opts: discard,data=journal
[    2.493859] initrd: mounting system rootfs at /halium-system
[    2.495488] EXT4-fs (loop0): couldn't mount as ext3 due to feature incompatibilities
[    2.495853] EXT4-fs (loop0): couldn't mount as ext2 due to feature incompatibilities
[    2.499162] EXT4-fs (loop0): mounted filesystem with ordered data mode. Opts: (null)
[    2.509579] initrd: mounting  /tmpmnt/rootfs.img (user mode)
[    2.512612] EXT4-fs (loop0): re-mounted. Opts: data=ordered
[    2.514577] initrd: mounting android system image (/tmpmnt/system.img) ro, in /android-system (system mode)
[    2.514633] initrd: mounting android system image from userdata partition
[    2.516658] EXT4-fs (loop1): couldn't mount as ext3 due to feature incompatibilities
[    2.516965] EXT4-fs (loop1): couldn't mount as ext2 due to feature incompatibilities
[    2.520051] EXT4-fs (loop1): mounted filesystem with ordered data mode. Opts: (null)
[    2.594062] mount: mounting /tmpmnt on /root/userdata failed: No such file or directory
[    2.594791] mount: mounting /android-rootfs on /root/var/lib/lxc/android/rootfs failed: No such file or directory
[    2.595530] mount: mounting none on /root/android failed: No such file or directory
[    2.596915] mount: mounting /root/userdata/android-data on /root/android/data failed: No such file or directory
[    2.605205] initrd: checking fstab /root/var/lib/lxc/android/rootfs/fstab* for additional mount points
[    2.608390] mount: mounting /root/userdata/cache on /root/android/cache failed: No such file or directory
[    2.609455] mount: mounting /android-system on /root/android/system failed: No such file or directory
[    2.833564] systemd[1]: Starting Remount Root and Kernel File Systems...
[    2.849017] systemd[1]: Started Remount Root and Kernel File Systems.
[    2.977146] systemd[1]: system.mount: Failed to check directory /system: No such file or directory
[    2.978920] systemd[1]: Mounting mount system.img...
[    2.984764] systemd[1]: system.mount: Mount process exited, code=exited status=32
[    2.984777] systemd[1]: system.mount: Failed with result 'exit-code'.
[    2.986117] systemd[1]: Failed to mount mount system.img.
[    2.987007] systemd[1]: system.mount: Failed to check directory /system: No such file or directory
[    3.002077] systemd[1]: Mounting mount system.img...
[    3.006279] systemd[1]: system.mount: Mount process exited, code=exited status=32
[    3.006293] systemd[1]: system.mount: Failed with result 'exit-code'.
[    3.007547] systemd[1]: Failed to mount mount system.img.
[    3.012382] systemd[1]: system.mount: Failed to check directory /system: No such file or directory
[    3.035222] systemd[1]: Mounting mount system.img...

**Comment by vanyasem** [comment]
@kozlovandrei please join https://t.me/halium to get support with your issue
