### ISSUE TITLE
d855

### ISSUE THREAD

**Issue by Pepitortue** [Halium/projectmanagement#66]
Tree: halium-7.1

- [x] Create manifest  https://github.com/Pepitortue/ubport_lge_d855/blob/master/lge_d855.xml 
- [ ] Boot image and system image build successfully
- [ ] Device boots into rootfs, `usb: Manufacturer: GNU/Linux Device` appears in `dmesg` on host.
- [ ] LXC container starts and does not crash
- [ ] libhybris tests
  * [ ] test_gps
  * [ ] test_hwcomposer
  * [ ] test_lights
  * [ ] test_vibrator
  * [ ] test_wifi
  * [ ] test_sensors
  * [ ] test_audio
  * [ ] test_camera
  * [ ] test_input
  * [ ] test_nfc
  * [ ] test_recorder

**Comment by JBBgameich** [comment]
Comment on your manifest: You can't use lineageos 15.1 device trees for Halium, you need to use 14.1. Also, please don't create a new repository for the manifest, but instead pull request it at https://github.com/halium/halium-devices.

**Comment by 110101011** [comment]
If you get stuck with this port and need help, i have an d855 as main phone. Just shout out and i see whatever i van do.

**Comment by Pepitortue** [comment]
I'm stuck here for now, while mka systemimage:
>    [ 28% 3897/13462]
>    (mv /home/pepito/halium/out/target/product/d855/obj/APPS/TimeService_intermediates/package.apk.signed /home/pepito/halium/out/target/product/d855/obj/APPS/TimeService_intermediates/package.apk )"
>    java.io.FileNotFoundException: --min-sdk-version (No such file or directory)
>    at java.io.FileInputStream.open0(Native Method)
>    at java.io.FileInputStream.open(FileInputStream.java:195)
>    at java.io.FileInputStream.(FileInputStream.java:138)
>    at com.android.signapk.SignApk.readPublicKey(SignApk.java:140)
>    at com.android.signapk.SignApk.main(SignApk.java:744)

It tries to rename halium/out/target/product/d855/obj/APPS/TimeService_intermediates/package.apk.signed
But the file does not exist.
There is only 
> package.apk.unsigned


~/halium$ jarsigner -verify halium/out/target/product/d855/obj/APPS/TimeService_intermediates/package.apk.unsigned
> jarsigner: Signature Block missing for CERT

Let see tomorrow if I can sign it or if I find a workaround
Any idea ?

**Comment by 110101011** [comment]
Remove all lines with .apk of .jar them from proprietary-files.txt which should be in your device tree. And rebuild, this should fix all apk/jar errrors in the build progress.

**Comment by JBBgameich** [comment]
Since today, apks should be automatically removed by the halium-devices setup script

**Comment by ghost** [comment]
any progress on this? Thanks

**Comment by 110101011** [comment]
I guess he stopped working on it, I'll see what I can do next week, I have a LG D-855 laying around doing nothing.

Just ask me for my progress next week, I case i forget to look at it, I'm a bit busy these days (my child takes up a lot of time :p)

**Comment by Pepitortue** [comment]
Hey,

Last time I was stuck at the ssh access after flashing the boot image, but didn't get time for this project anymore. 
Now that OTA-4 has been released, I'm back and will try to make ubports boot this time.
Would be great to work together :)

**Comment by 110101011** [comment]
So you did get SSH access and did you run the libhybris tests?

**Comment by Pepitortue** [comment]
No I didn't, the device wasn't showing in terminal. I couldn't run any libhybris test.
I was stuck at this step.

**Comment by 110101011** [comment]
Ok I'll clean up my desk and see if I can help in a couple of days, it at least compiled and boots which is good. So it's only debugging now, to see if and where in the boot process it fails.

**Comment by Pepitortue** [comment]
Hi,

Just tried to build again.

mkbootimg and hybris-boot worked but I'm stuck on this error with the system image : 

`Building DTBs
make: Entering directory '/home/pepito/halium/kernel/lge/g3'
make[2]: Nothing to be done for 'arch/arm/boot/dtbs'.
make: Leaving directory '/home/pepito/halium/kernel/lge/g3'
[  9% 1260/13346] Lex: libsepol_32 <= external/selinux/libsepol/cil/src/cil_lexer.l
FAILED: /home/pepito/halium/out/host/linux-x86/obj32/SHARED_LIBRARIES/libsepol_intermediates/cil/src/cil_lexer.c 
/bin/bash -c "prebuilts/misc/linux-x86/flex/flex-2.5.39 -o/home/pepito/halium/out/host/linux-x86/obj32/SHARED_LIBRARIES/libsepol_intermediates/cil/src/cil_lexer.c external/selinux/libsepol/cil/src/cil_lexer.l"
flex-2.5.39: loadlocale.c:130: _nl_intern_locale_data: Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
Aborted (core dumped)
[  9% 1260/13346] host C: libsqlite_32 <= external/sqlite/dist/sqlite3.c
ninja: build stopped: subcommand failed.
build/core/ninja.mk:151: recipe for target 'ninja_wrapper' failed
make: *** [ninja_wrapper] Error 1
make: Leaving directory '/home/pepito/halium'

#### make failed to build some targets (01:30 (mm:ss)) ####
`


I read that it might be caused by insufficient amount of RAM (I've put 10GB to this VM). Some says that 16GB of RAM is required, but last time (in march) I used only 8GB and didn't have this error.
Any idea ?

**Comment by jbruechert** [comment]
This is a wierd bug which can often be fixed by either setting the language to default/english `LANG=C mka hybris-boot` or by using the host flex binary `USE_HOST_FLEX=true mka hybris-boot`

**Comment by Pepitortue** [comment]
LANG=C mka worked, thanks !

**Comment by Pepitortue** [comment]
Ok, I will stop for today.
For info I've switched to the ubports rootfs, I don't know if you support (tolerate) it here. 
I will try halium's rootfs next week.

### So far on halium part : 
Made all the required config (fixup-mountpoints etc...)
All mka are successful no error

### On ubports part : 
Kernel config set
No more error with the check script
halium-boot and systemimage built successfully
Flash the halium-boot image
Use the halium-install script with ut parameter to copy the ubports rootfs and system image to /data

Got instant secure boot, so no ssh nor boot.
Might be due to the modified kernel config in : 
`kernel/lge/g3/arch/arm/configs/msm8974_defconfig`

**Comment by Pepitortue** [comment]
Ok so I'm back on it, with halium rootfs this time.
All `mka` wen successfull.
Flashed the boot and pushed the `rootfs.img` and `system.img` to` /data/`
I had to bump my boot using Mr.bump script to prevent secure boot issue.

I finally got telnet access to the device.
Here is my issue : 
```
~ # cat diagnosis.log
No /proc/config.gz. Enable CONFIG_IKCONFIG and CONFIG_IKCONFIG_PROC
```

That's strange, I've made this change in the kernel, under : 
`halium/kernel/lge/g3/arch/arm/configs/msm8974_defconfig `

```
CONFIG_IKCONFIG=y
CONFIG_IKCONFIG_PROC=y
```

Here is my `diagnosis.log` and `init.log` : 

https://pastebin.com/raw/2TSJndEF


I will check tomorrow, if you have any suggestion in the mean time, don't hesitate.

**Comment by Pepitortue** [comment]
Ok, I now have **ssh** access to the GNU device !

It failed before because I used the `msm8974_defconfig` kernel which is not the good one... :facepalm:
I've rebuild everything using the `lineageos_d855_defconfig` kernel and it works :)

**Comment by Pepitortue** [comment]
I tried to update the device in order to get hwcomposer to work but get this error : 
```
root@localhost:/# apt-get upgrade
Reading package lists... Error!
E: Write error - write (28: No space left on device)
E: IO Error saving source cache
E: The package lists or status file could not be parsed or opened.

```

I have far enough space on the device : 
```
root@localhost:/# df -h
Filesystem        Size  Used Avail Use% Mounted on
/dev/block/loop0 1008M 1008M     0 100% /
/dev/mmcblk0p43    12G  1.4G  9.9G  13% /data
devtmpfs          734M     0  734M   0% /dev
tmpfs             912M     0  912M   0% /dev/shm
tmpfs             912M   26M  887M   3% /run
tmpfs             5.0M     0  5.0M   0% /run/lock
tmpfs             912M     0  912M   0% /sys/fs/cgroup
/dev/loop1        198M  198M  4.0K 100% /system
/dev/mmcblk0p41   599M   11M  589M   2% /cache
/dev/mmcblk0p19    32M  4.2M   28M  14% /persist
/dev/mmcblk0p1     64M   57M  7.1M  90% /firmware
/dev/mmcblk0p37   7.9M  4.1M  3.8M  52% /sns
/dev/mmcblk0p36   7.9M  4.6M  3.4M  58% /persist-lg
/dev/mmcblk0p38    32M  6.1M   26M  20% /mpt
```

It seems that it tries to write datas to `/dev/block/loop0` which is full.
Where does this device comes from ?
Do I made a mistake with the fix_mounting_points or is this normal ?

For info I used this script to create the rootfs.img and system.img : 
https://github.com/JBBgameich/halium-install/releases

Because the official one from halium (https://github.com/Halium/halium-scripts) gave me an error like :
`No space left on the device to write 51 blocks`

**Comment by jbruechert** [comment]
The loop device is created when mounting /data/rootfs.img. If you want to increase it's size, you need to use `resize2fs` on /data/rootfs.img

**Comment by Pepitortue** [comment]
Still the same issue with 2GB on the rootfs. I have 0 bytes of space.
I can't even use the <tab> key in the shell as it needs to create a temp file :D
Is this due to those lines at the start of mka ? : 

```
Checking build tools versions...
frameworks/av/camera/cameraserver/Android.mk:18: Target has integrated cameraserver into mediaserver. This is weakening security measures introduced in 7.0
halium/hybris-boot/Android.mk:69: ********************* /boot appears to live on /dev/block/platform/msm_sdcc.1/by-name/boot
halium/hybris-boot/Android.mk:70: ********************* /data appears to live on /dev/block/platform/msm_sdcc.1/by-name/userdata
No private recovery resources for TARGET_DEVICE d855
build/core/Makefile:34: warning: overriding commands for target `/home/pepito/halium/out/target/product/d855/system/lib/librmnetctl.so'
build/core/base_rules.mk:316: warning: ignoring old commands for target `/home/pepito/halium/out/target/product/d855/system/lib/librmnetctl.so'
Starting build with ninja
```
I never considered those as an error as the mount points showed seems correct and the mka is a success.

**Comment by Pepitortue** [comment]
Hi,

I just made an **Issue** part in the main post (last part) to not spam the thread.
Will work on it this week. In the mean time if someone have an idea/fix... 😃

**Comment by 110101011** [comment]
/data/rootfs.img seems to be 200mb instead of 2gig, did it resize correctly

**Comment by Pepitortue** [comment]
I used JBB's standalone script which contains : 
https://github.com/JBBgameich/halium-install/
I changed the variable of the shell script `functions/distributions.sh` : 
```
halium)
	IMAGE_SIZE=1G
	;;
```
which is used to "expand" the rootfs : 
`qemu-img create -f raw $IMAGE_DIR/rootfs.img $image_size`

At the end the rootfs was : 
```
$ du -sh *
2,0G	rootfs.img
213M	system.img
```
I though it did the job. I still need to use the resize2fs command ?
The system.img is 213M and mount to /system. (not the rootfs, right ?)
It's sized by default. Will try to make it 2G as in lineageOS vanilla.

**Comment by doniks** [comment]
seems you set IMAGE_SIZE (all caps) but you use image_size (lower caps)

**Comment by ezs123** [comment]
Does this devlopment have any updates?
Does it work?
